"""initial migration

Revision ID: d93317ab50ce
Revises: 
Create Date: 2026-06-29 11:30:45.166879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93317ab50ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('location', sa.String(), nullable=True))
    op.drop_constraint(op.f('companies_job_id_fkey'), 'companies', type_='foreignkey')
    op.drop_column('companies', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('companies_job_id_fkey'), 'companies', 'jobs', ['job_id'], ['id'])
    op.drop_column('companies', 'location')
    # ### end Alembic commands ###
